name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+3
  video_player: ^2.4.6
  fl_chart: ^0.69.0  
  http: ^1.2.2
  url_launcher: ^6.0.9

  
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  
 

  
  

 
  #flutter_lints: ^4.0.0


flutter:
  assets:
  - assets/images/logo.png
  - assets/images/default.jpg
  - assets/images/noe.png
  - assets/credentials/credentials.json
  
  uses-material-design: true

 